### ISSUE TITLE
Form Engine起動後、ProtocolErrorが発生しForm Engineが停止してしまう

### ISSUE THREAD

**Issue by nishim** [nishishimamoto-shu/form-engine#1]
## 現状
以下のようなChrome Dev Tools関連でタイムアウトが発生すると、処理中のチャンク全体の処理が完了後、Form Engineが終了します。
発生頻度は1チャンク〜10弱とまちまちです。
発生した場合、再度Form Engineを実行しています。

```bash
ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
    at new Callback (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
    at CallbackRegistry.create (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
    at Connection._rawSend (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
    at CdpCDPSession.send (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
    at /Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:335:33
    at #withTransaction (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:248:19)
    at CdpMouse.up (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:330:36)
    at CdpMouse.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:364:27)
    at CdpElementHandle.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:711:43)
Submit result: ERROR
ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
    at new Callback (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
    at CallbackRegistry.create (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
    at Connection._rawSend (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
    at CdpCDPSession.send (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
    at /Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:335:33
    at #withTransaction (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:248:19)
    at CdpMouse.up (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:330:36)
    at CdpMouse.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:364:27)
    at CdpElementHandle.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:711:43)
Submit result: ERROR
ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
    at new Callback (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
    at CallbackRegistry.create (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
    at Connection._rawSend (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
    at CdpCDPSession.send (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
    at /Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:335:33
    at #withTransaction (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:248:19)
    at CdpMouse.up (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:330:36)
    at CdpMouse.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Input.js:364:27)
    at CdpElementHandle.click (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:711:43)
Submit result: ERROR
An error occurred: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
Ending processOnConfirm function
Error occurred while processing page. url: https://www2.kanden.ne.jp/kanso/inquiry.html
ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
    at new Callback (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
    at CallbackRegistry.create (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
    at Connection._rawSend (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
    at CdpCDPSession.send (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
    at #evaluate (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:211:50)
    at async ExecutionContext.evaluate (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:129:16)
    at async CdpFrame.evaluate (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:370:20)
    at async CdpPage.evaluate (/Users/yuji/dev/form-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:872:20)
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open ''
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: ''
}

Node.js v18.15.0
yuji@macbook: ~/dev/form-engine (main *%=)$ 
```

## 対応いただきたい内容
与えられたリストを、手動での再実行なしに処理しきれるようにしていただきたいです。

最終的にはDocker / ECSで動作させたいので、
- main.jsでは1チャンクまたは1URLを処理するような作りとする
- main.jsを呼び出す仕組みを別途作る
あたりが良いのではと考えていますが、他に良い方法があればそれでも構いません。

**Comment by chocopun** [comment]
最後まで動き切ってほしい。
